--- # docuemtn start

#########################
# DEFAULT CONFIGURATION #
#########################

# Here goes all the configuration that is not specific
# to an environment.

server:
  port: 3000

db:
  type: 'postgres'
  port: 5432
  database: 'taskmanagement'

jwt:
  expiresIn: 3600
